name: FastAPI Deployment

on:
  push:
    branches:
      - main  # Only trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run FastAPI app (for test)
      run: |
        uvicorn app:app --host 0.0.0.0 --port 8000 --reload &
        sleep 5  # Give server time to start
        curl -f http://127.0.0.1:8000/docs || exit 1
