name: FastAPI CI/CD to EC2

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Pull repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Python setup for test run
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Test FastAPI launch
    - name: Run FastAPI app (test startup only)
      run: |
        uvicorn app:app --host 0.0.0.0 --port 8000 --reload &
        sleep 5
        curl -f http://127.0.0.1:8000/docs || exit 1

    # Step 5: Deploy to AWS EC2 using SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          # If repo already exists, pull latest code; otherwise, clone it
          cd iris-api || git clone https://github.com/<your-username>/iris-api.git && cd iris-api
          git pull origin main

          # Build and restart Docker container
          docker build -t iris-api .
          docker stop iris-api || true
          docker rm iris-api || true
          docker run -d -p 8000:8000 --name iris-api iris-api
